# Dockerfile
# preferred node version chosen here (Active LTS = 22 as of 10/2024)
FROM public.ecr.aws/docker/library/node:22.1.0-alpine3.19

# Create the directory on the node image
# where our Next.js app will live
RUN mkdir -p /app

# Set /app as the working directory in container
WORKDIR /app

# Install bash and curl so we can use session manager to attach to the container
# and perform container health checks
RUN apk add --no-cache bash curl

# Copy package.json and package-lock.json
# to the /app working directory
COPY package.json ./

# Install dependencies in /app
RUN npm ci

# Copy the rest of our Next.js folder into /app
COPY . .

# Ensure port 3000 is accessible to our system
EXPOSE 3000

# Command to run the Next.js app in development mode
CMD ["npm", "run", "dev"]