# Dockerfile
# preferred node version chosen here (LTS = 20.9.0 as of 10/24/2023)
FROM public.ecr.aws/docker/library/node:lts-alpine3.19

# Create the directory on the node image
# where our Next.js app will live
RUN mkdir -p /app

# Set /app as the working directory in container
WORKDIR /app

ENV NEXT_PUBLIC_SERVER_ENDPOINT="https://ui.dmphub.uc3dev.cdlib.net"

# Copy package.json and package-lock.json
# to the /app working directory
COPY package.json ./

# Install dependencies in /app
RUN npm install

# Copy the rest of our Next.js folder into /app
COPY . .

# Ensure port 3000 is accessible to our system
EXPOSE 3000

# Command to run the Next.js app in development mode
CMD ["npm", "run", "dev"]