import { Status, WorkType } from "@/app/types";

export const DEMO_WORKS = [
  {
    dmpDoi: "",
    score: 0.3,
    work: {
      doi: "10.1126/fake.2025.084512",
      type: WorkType.Article,
      title: "NeuroSynthetics: Toward Biologically-Inspired Cognitive Robotics",
      publicationDate: new Date(2020, 4, 15),
      containerTitle: "Journal of Future Robotics Research",
      authors: [
        {
          firstInitial: "A",
          givenName: "Alyssa",
          middleInitial: "M",
          middleName: "Marie",
          surname: "Langston",
          full: null,
          orcid: "0000-0003-1234-5678",
        },
        {
          firstInitial: "D",
          givenName: "David",
          middleInitial: null,
          middleName: null,
          surname: "Choi",
          full: null,
          orcid: null,
        },
        {
          firstInitial: "L",
          givenName: "Liam",
          middleInitial: "J",
          middleName: "James",
          surname: "Patel",
          full: null,
          orcid: "0000-0002-9876-5432",
        },
        {
          firstInitial: "N",
          givenName: "Natalie",
          middleInitial: null,
          middleName: null,
          surname: "Martinez",
          full: null,
          orcid: null,
        },
        {
          firstInitial: "S",
          givenName: "Samuel",
          middleInitial: null,
          middleName: null,
          surname: "Okafor",
          full: null,
          orcid: "0000-0001-8765-4321",
        },
        {
          firstInitial: "J",
          givenName: "Jasmine",
          middleInitial: null,
          middleName: null,
          surname: "Reynolds",
          full: null,
          orcid: null,
        },
        {
          firstInitial: "K",
          givenName: "Kieran",
          middleInitial: null,
          middleName: null,
          surname: "Wang",
          full: null,
          orcid: "0000-0004-2299-1122",
        },
        {
          firstInitial: "E",
          givenName: "Emily",
          middleInitial: "R",
          middleName: "Rose",
          surname: "Carter",
          full: null,
          orcid: null,
        },
        {
          firstInitial: "O",
          givenName: "Omar",
          middleInitial: null,
          middleName: null,
          surname: "Hassan",
          full: null,
          orcid: "0000-0005-6677-8899",
        },
        {
          firstInitial: "T",
          givenName: "Talia",
          middleInitial: null,
          middleName: null,
          surname: "Nguyen",
          full: null,
          orcid: null,
        },
      ],
      institutions: [
        { ror: "042nb2s44", name: "Massachusetts Institute of Technology" },
        { ror: "05x2bcf33", name: "Carnegie Mellon University" },
      ],
      funders: [
        { ror: "021nxhr62", name: "U.S. National Science Foundation" },
        { ror: "01cwqze88", name: "National Institutes of Health" },
      ],
      awardIds: ["2357894", "R01 HL201245-02"],
      source: { name: "OpenAlex", url: "https://openalex.org/works/w2060245136" },
    },
    dateFound: new Date(2025, 7, 21),
    status: Status.Pending,
    match: {
      doi: false,
      title: null, //"<mark>NeuroSynthetics</mark>: Toward Biologically-Inspired <mark>Cognitive Robotics</mark>",
      abstract: [],
      awardIds: [],
      authors: [],
      institutions: [1],
      funders: [0],
    },
    dateReviewed: null,
  },
  {
    dmpDoi: "",
    score: 0.6,
    work: {
      doi: "10.1016/fake.2025.293748",
      type: WorkType.Dataset,
      title: "Synthetic Empathy: Emotional Intelligence in Autonomous Agents",
      publicationDate: new Date(2024, 2, 10),
      containerTitle: "Artificial Intelligence & Society",
      authors: [
        {
          firstInitial: "M",
          givenName: "Marcus",
          middleInitial: null,
          middleName: null,
          surname: "Nguyen",
          full: null,
          orcid: null,
        },
        {
          firstInitial: "R",
          givenName: "Rebecca",
          middleInitial: "L",
          middleName: "Lee",
          surname: "Stone",
          full: null,
          orcid: "0000-0001-2233-4455",
        },
        {
          firstInitial: "S",
          givenName: "Sofia",
          middleInitial: null,
          middleName: null,
          surname: "Delgado",
          full: null,
          orcid: "0000-0004-1122-3344",
        },
      ],
      institutions: [
        { ror: "00f54p054", name: "Stanford University" },
        { ror: "01an7q238", name: "University of California, Berkeley" },
      ],
      funders: [{ ror: "021nxhr62", name: "U.S. National Science Foundation" }],
      awardIds: ["2145023"],
      source: { name: "OpenAlex", url: "https://openalex.org/works/w2060245136" },
    },
    dateFound: new Date(2025, 7, 15),
    status: Status.Pending,
    match: {
      doi: false,
      title: "<mark>Synthetic Empathy</mark>: <mark>Emotional Intelligence</mark> in <mark>Autonomous Agents</mark>",
      abstract: [
        // "... the need for systems with <mark>emotional intelligence</mark> is critical. We propose a hybrid architecture that enables <mark>autonomous agents</mark> to recognize, model, and simulate empathetic responses.",
        // "Evaluations in human-agent interaction studies reveal that <mark>synthetic empathy</mark> increases user trust and engagement...",
      ],
      awardIds: [],
      authors: [0, 3],
      institutions: [0, 1],
      funders: [0],
    },
    dateReviewed: null,
  },
  {
    dmpDoi: "",
    score: 0.8,
    work: {
      doi: "10.5555/fake.2025.778899",
      type: WorkType.Book,
      title: "Quantum-Tuned Perception Systems for Next-Gen Robots",
      publicationDate: new Date(2025, 6, 28),
      containerTitle: "IEEE Transactions on Robotics",
      authors: [
        {
          firstInitial: "K",
          givenName: "Kaitlyn",
          middleInitial: null,
          middleName: null,
          surname: "Zhao",
          full: null,
          orcid: "0000-0003-8765-4321",
        },
        {
          firstInitial: "J",
          givenName: "Jonathan",
          middleInitial: "B",
          middleName: "Benjamin",
          surname: "Harris",
          full: null,
          orcid: null,
        },
        {
          firstInitial: "T",
          givenName: "Travis",
          middleInitial: null,
          middleName: null,
          surname: "Mendoza",
          full: null,
          orcid: null,
        },
        {
          firstInitial: "M",
          givenName: "Maya",
          middleInitial: null,
          middleName: null,
          surname: "Foster",
          full: null,
          orcid: "0000-0009-5555-4444",
        },
        {
          firstInitial: "I",
          givenName: "Isaiah",
          middleInitial: "K",
          middleName: "Kai",
          surname: "Turner",
          full: null,
          orcid: null,
        },
        {
          firstInitial: "B",
          givenName: "Brooklyn",
          middleInitial: null,
          middleName: null,
          surname: "Singh",
          full: null,
          orcid: "0000-0002-7777-3333",
        },
        {
          firstInitial: "G",
          givenName: "Gabriel",
          middleInitial: null,
          middleName: null,
          surname: "Morrison",
          full: null,
          orcid: null,
        },
        {
          firstInitial: "Z",
          givenName: "Zara",
          middleInitial: "L",
          middleName: "Lyn",
          surname: "Kim",
          full: null,
          orcid: "0000-0006-1234-4567",
        },
        {
          firstInitial: "R",
          givenName: "Riley",
          middleInitial: null,
          middleName: null,
          surname: "Bennett",
          full: null,
          orcid: null,
        },
        {
          firstInitial: "C",
          givenName: "Caden",
          middleInitial: null,
          middleName: null,
          surname: "Thomas",
          full: null,
          orcid: "0000-0008-9080-1000",
        },
        {
          firstInitial: "S",
          givenName: "Skylar",
          middleInitial: null,
          middleName: null,
          surname: "Diaz",
          full: null,
          orcid: null,
        },
        {
          firstInitial: "H",
          givenName: "Hudson",
          middleInitial: "J",
          middleName: "Jude",
          surname: "Lee",
          full: null,
          orcid: "0000-0001-5151-6262",
        },
        {
          firstInitial: "F",
          givenName: "Faith",
          middleInitial: null,
          middleName: null,
          surname: "Andrews",
          full: null,
          orcid: null,
        },
      ],
      institutions: [
        { ror: "05dxps055", name: "California Institute of Technology" },
        { ror: "00jmfr291", name: "University of Michigan" },
      ],
      funders: [
        { ror: "021nxhr62", name: "U.S. National Science Foundation" },
        { ror: "01cwqze88", name: "National Institutes of Health" },
      ],
      awardIds: ["2139987", "R01 NS987654-01"],
      source: { name: "DataCite", url: "https://commons.datacite.org/doi.org/10.5555/fake.2025.778899" },
    },
    dateFound: new Date(2025, 7, 1),
    status: Status.Pending,
    match: {
      doi: true,
      title: "<mark>Quantum-Tuned</mark> <mark>Perception Systems</mark> for <mark>Next-Gen Robots</mark>",
      abstract: [
        "We present a novel framework that leverages <mark>quantum-tuned</mark> signal processing to enhance <mark>robotic perception systems</mark>. By integrating low-power quantum sensors...",
        "...opening avenues for <mark>next-generation autonomous robotics</mark>.",
      ],
      awardIds: [0],
      authors: [0, 2, 4, 8, 12],
      institutions: [0, 1],
      funders: [0, 1],
    },
    dateReviewed: null,
  },
  {
    dmpDoi: "",
    score: 0.1,
    work: {
      doi: "10.3847/fake.2025.245187",
      type: WorkType.Dissertation,
      title: "Stellar Cartography and the Dynamic Mapping of Interstellar Gas Clouds",
      publicationDate: new Date(2025, 3, 20),
      containerTitle: "Astrophysical Journal Letters",
      authors: [
        {
          firstInitial: "C",
          givenName: "Clara",
          middleInitial: null,
          middleName: null,
          surname: "Montague",
          full: null,
          orcid: "0000-0003-7890-1122",
        },
        {
          firstInitial: "A",
          givenName: "Arjun",
          middleInitial: null,
          middleName: null,
          surname: "Desai",
          full: null,
          orcid: null,
        },
        {
          firstInitial: "E",
          givenName: "Elena",
          middleInitial: null,
          middleName: null,
          surname: "Ng",
          full: null,
          orcid: "0000-0002-4545-1212",
        },
        {
          firstInitial: "M",
          givenName: "Mateo",
          middleInitial: null,
          middleName: null,
          surname: "Vargas",
          full: null,
          orcid: null,
        },
      ],
      institutions: [
        { ror: "01an7q238", name: "Carnegie Mellon University" },
        { ror: "02y2hzk54", name: "Massachusetts Institute of Technology" },
      ],
      funders: [{ ror: "021nxhr62", name: "U.S. National Science Foundation" }],
      awardIds: ["2451873"],
      source: { name: "OpenAlex", url: "https://openalex.org/works/w2060245136" },
    },
    dateFound: new Date(2025, 4, 1),
    status: Status.Discarded,
    match: {
      doi: false,
      title: null,
      abstract: [],
      awardIds: [],
      authors: [],
      institutions: [1],
      funders: [0],
    },
    dateReviewed: new Date(2025, 4, 2),
  },
  {
    dmpDoi: "",
    score: 0.15,
    work: {
      doi: "10.1016/fake.2025.998877",
      type: WorkType.Report,
      title: "Cryovolcanic Activity on Enceladus: Implications for Subsurface Habitability",
      publicationDate: new Date(2025, 5, 12),
      containerTitle: "Planetary Science Journal",
      authors: [
        {
          firstInitial: "J",
          givenName: "Julian",
          middleInitial: null,
          middleName: null,
          surname: "Foster",
          full: null,
          orcid: "0000-0001-1122-3344",
        },
        {
          firstInitial: "R",
          givenName: "Rina",
          middleInitial: null,
          middleName: null,
          surname: "Takahashi",
          full: null,
          orcid: null,
        },
        {
          firstInitial: "B",
          givenName: "Blake",
          middleInitial: null,
          middleName: null,
          surname: "O'Connor",
          full: null,
          orcid: "0000-0009-8888-7777",
        },
      ],
      institutions: [{ ror: "00b0x6745", name: "California Institute of Technology" }],
      funders: [
        { ror: "021nxhr62", name: "U.S. National Science Foundation" },
        { ror: "02e2c6t66", name: "National Institutes of Health" },
      ],
      awardIds: ["2501482", "R01 AI302114-01"],
      source: { name: "OpenAlex", url: "https://openalex.org/works/w2060245136" },
    },
    dateFound: new Date(2025, 1, 1),
    status: Status.Discarded,
    match: {
      doi: false,
      title: null,
      abstract: [],
      awardIds: [],
      authors: [],
      institutions: [],
      funders: [0],
    },
    dateReviewed: new Date(2025, 1, 2),
  },
  {
    dmpDoi: "",
    score: 0.89,
    work: {
      doi: "10.5555/fake.2025.661100",
      type: WorkType.Article,
      title: "Real-Time Sim2Real Transfer for Bipedal Robot Gait Adaptation",
      publicationDate: new Date(2025, 7, 5),
      containerTitle: "Frontiers in Robotics and AI",
      authors: [
        {
          firstInitial: "J",
          givenName: "Jordan",
          middleInitial: null,
          middleName: null,
          surname: "Ali",
          full: null,
          orcid: "0000-0006-7890-1234",
        },
        {
          firstInitial: "S",
          givenName: "Samantha",
          middleInitial: null,
          middleName: null,
          surname: "Rogers",
          full: null,
          orcid: null,
        },
        {
          firstInitial: "C",
          givenName: "Carlos",
          middleInitial: "D",
          middleName: "Diego",
          surname: "Ramirez",
          full: null,
          orcid: "0000-0005-5555-6789",
        },
        {
          firstInitial: "L",
          givenName: "Leila",
          middleInitial: null,
          middleName: null,
          surname: "Chen",
          full: null,
          orcid: null,
        },
      ],
      institutions: [{ ror: "05dxps055", name: "California Institute of Technology" }],
      funders: [
        { ror: "021nxhr62", name: "U.S. National Science Foundation" },
        { ror: "01cwqze88", name: "National Institutes of Health" },
      ],
      awardIds: ["2288994", "R01 EB765432-03"],
      source: {
        name: "DataCite",
        url: "https://commons.datacite.org/doi.org/10.5555/fake.2025.661100",
      },
    },
    dateFound: new Date(2025, 6, 1),
    status: Status.Related,
    match: {
      doi: true,
      title: "Real-Time <mark>Sim2Real</mark> Transfer for <mark>Bipedal Robot</mark> <mark>Gait Adaptation</mark>",
      abstract: [
        "We propose a <mark>Sim2Real</mark> transfer technique for enabling dynamic <mark>bipedal robot</mark> locomotion across varying terrain conditions without retraining.",
        "Our results demonstrate improved <mark>gait adaptation</mark> using real-time sensory corrections during transitions between simulated and physical environments.",
      ],
      awardIds: [0],
      authors: [0, 2],
      institutions: [0],
      funders: [0, 1],
    },
    dateReviewed: new Date(2025, 6, 2)
  },
  {
    dmpDoi: "",
    score: 0.92,
    work: {
      doi: "10.5555/fake.2025.443322",
      type: WorkType.Dataset,
      title: "Multisensory Feedback Loops for Dexterous Robotic Manipulation",
      publicationDate: new Date(2025, 2, 18),
      containerTitle: "IEEE Robotics and Automation Letters",
      authors: [
        {
          firstInitial: "A",
          givenName: "Amira",
          middleInitial: null,
          middleName: null,
          surname: "Nguyen",
          full: null,
          orcid: "0000-0003-2244-5566",
        },
        {
          firstInitial: "T",
          givenName: "Trevor",
          middleInitial: null,
          middleName: null,
          surname: "Shaw",
          full: null,
          orcid: null,
        },
        {
          firstInitial: "D",
          givenName: "Daniel",
          middleInitial: "S",
          middleName: "Scott",
          surname: "Lewis",
          full: null,
          orcid: "0000-0002-1111-3333",
        },
      ],
      institutions: [{ ror: "01an7q238", name: "Carnegie Mellon University" }],
      funders: [{ ror: "021nxhr62", name: "U.S. National Science Foundation" }],
      awardIds: ["2356781"],
      source: {
        name: "DataCite",
        url: "https://commons.datacite.org/doi.org/10.5555/fake.2025.443322",
      },
    },
    dateFound: new Date(2025, 3, 1),
    status: Status.Related,
    match: {
      doi: true,
      title: "<mark>Multisensory</mark> Feedback Loops for <mark>Dexterous</mark> <mark>Robotic Manipulation</mark>",
      abstract: [
        "We present a control architecture that fuses <mark>multisensory</mark> data from tactile, visual, and proprioceptive inputs to enable <mark>dexterous</mark> <mark>robotic manipulation</mark> in unstructured environments.",
        "The loop-based system enhances object interaction stability and allows fine-tuned grasping strategies.",
      ],
      awardIds: [0],
      authors: [0, 2],
      institutions: [0],
      funders: [0],
    },
    dateReviewed: new Date(2025, 3, 2),
  },
];
