import type { Metadata } from "next";
import { useImmerReducer } from 'use-immer';
import { Poppins } from "next/font/google";
import '@fortawesome/fontawesome-svg-core/styles.css'
import Header from "@/components/Header";
import SubHeader from "@/components/SubHeader";
import Notifications from "@/components/Notifications";
import Footer from "@/components/footer";
import "./globals.scss";


const poppins_init = Poppins({
  subsets: ["latin"],
  weight: ['500', '600'],
  variable: '--font-poppins',
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={poppins_init.className}>
        <a href="#maincontent" className="c-skipnav dmpui-skipnav">Skip to main content</a>
        <Header />
        <SubHeader />
        <Notifications />
        <div id="App">
          <main id="maincontent">{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
