import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import '@fortawesome/fontawesome-svg-core/styles.css'
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SubHeader from "@/components/SubHeader";
import {ApolloWrapper} from "@/lib/graphql/apollo-wrapper";
import {AuthProvider} from "@/context/AuthContext";
import {CsrfProvider} from "@/context/CsrfContext";
import "@/styles/globals.scss";

const font_sans_serif = Poppins({
  subsets: ["latin"],
  weight: ['400', '600'],
  variable: '--font-sans-serif',
});

export const metadata: Metadata = {
  title: "DMP",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={font_sans_serif.variable}>
    <head>
      <link
        rel="preload"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
        as="style"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
        rel="stylesheet"
      />
    </head>
    <body className={font_sans_serif.className}>
    <a href="#mainContent" className="skip-nav">Skip to main content</a>
    <AuthProvider>
      <CsrfProvider>
        <Header/>
        <SubHeader/>
        <div id="App">
          <main id="mainContent"><ApolloWrapper>{children}</ApolloWrapper>
          </main>
        </div>
        <Footer/>
      </CsrfProvider>
    </AuthProvider>
    </body>
    </html>
  );
}
